[events]
OnKeyDown = "A key was physically pressed."
OnKeyUp = "A key was physically released."
OnKeyPressed = "A key was logically pressed."
OnTagUnknown = "An unknown RFID / NFC tag was detected."
"OnKeyDown_[pin]" = "Like OnKeyDown, but specifically for pin [pin]."
"OnKeyUp_[pin]" = "Like OnKeyUp, but specifically for pin [pin]."
"OnKeyPressed_[pin]" = "Like OnKeyPressed, but specifically for pin [pin]."
"OnKeyDown_[keyboard].[pin]" = "Like OnKeyDown, but for pin [pin] of keyboard [keyboard]."
"OnKeyUp_[keyboard].[pin]" = "Like OnKeyUp, but for pin [pin] of keyboard [keyboard]."
"OnKeyPressed_[keyboard].[pin]" = "Like OnKeyPressed, but for pin [pin] of keyboard [keyboard]."

[config.keyboard."*"]
_description = "Configuration for keyboard *"

[config.keyboard."*".type]
_description = "The type of keyboard"
_type = "enum"
_enumcls = "doorpi.keyboard.enums.KeyboardType"
_default = "filesystem"

[config.keyboard."*".bouncetime]
_description = "Software debounce time (ms)"
_type = "int"
_default = 100
_min = 0

[config.keyboard."*".polarity]
_description = "The keyboard's logic polarity ('LOW'/'HIGH')"
_type = "enum"
_enumcls = "doorpi.keyboard.enums.Polarity"
_default = "HIGH"

[config.keyboard."*".pressed_on_key_down]
_description = "Fire OnKeyPressed when the key is pushed down (false: when it is released)"
_type = "bool"
_default = true

[config.keyboard."*".reset_input]
_description = "[filesystem] Reset input files after reading them"
_type = "bool"
_default = true

[config.keyboard."*".inputdir]
_description = "[filesystem] Directory holding the input files"
_type = "path"
_default = ""

[config.keyboard."*".outputdir]
_description = "[filesystem] Directory holding the output files"
_type = "path"
_default = ""

[config.keyboard."*".mode]
_description = "[gpio] Pin numbering mode (BOARD is recommended)"
_type = "enum"
_enumcls = "doorpi.keyboard.enums.GPIOMode"
_default = "BOARD"

[config.keyboard."*".pull_up_down]
_description = "[gpio] Configure internal pull-up/down resistors"
_type = "enum"
_enumcls = "doorpi.keyboard.enums.GPIOPull"
_default = "OFF"

[config.keyboard."*".port]
_description = "[pn532/rdm6300/serial] Serial port to connect"
_type = "path"
_default = ""

[config.keyboard."*".baudrate]
_description = "[serial] Baud rate of the serial connection"
_type = "int"
_default = 9600

[config.keyboard."*".input_stop_flag]
_description = "[serial] Stop flag after receiving input; Default: newline"
_type = "string"
_default = "\n"

[config.keyboard."*".input_buffer_size]
_description = "[serial] Maximum amount of characters to buffer"
_type = "int"
_default = 255

[config.keyboard."*".output_stop_flag]
_description = "[serial] Stop flag after sending output; Default: newline"
_type = "string"
_default = "\n"

[config.keyboard."*".input."*"]
_description = "Actions to fire when input {2} is activated on keyboard {1}"
_type = "list"
_membertype = "string"
_default = []

[config.keyboard."*".output."*"]
_description = "Define an alias for key *; a unique name for use in actions like 'out:<alias>'."
_type = "string"
_default = ""
