[config.snapshots.directory]
_description = "Where to store snapshots"
_type = "path"
_default = "snapshots"

[config.snapshots.keep]
_description = "Maximum number of snapshots to keep"
_default = 10
_min = 1

[config.snapshots.width]
_description = "Desired horizontal snapshot resolution"
_default = 0
_min = 0
